### ISSUE TITLE
ClassCastException in the FiseTranslator

### ISSUE THREAD

**Issue by westei** [fusepoolP3/p3-datatxt-stanbol#1]
The trace

```
Caused by: java.lang.ClassCastException: org.apache.clerezza.rdf.core.UriRef cannot be cast to java.io.Serializable
    at eu.spaziodati.datatxt.stanbol.enhancer.engines.translators.FiseTranslator.translate(FiseTranslator.java:47)
    at eu.spaziodati.datatxt.stanbol.enhancer.engines.DatatxtNexEngine.computeEnhancements(DatatxtNexEngine.java:160)
```

This is cause by this logging in the following code snipet

```
public void translate(Pair<UriRef, MGraph> item, EnhancementEngine engine, String text, DatatxtResponse datatxtResponse) {
    LOG.info(String.format("DatatxtAnnotator: Enhance ContentItem with FISE Annotations: ContentItem=%s, " +
            "DatatxtResponse=%s", (item != null ? item.getKey() : item), GSON.toJson(datatxtResponse)));
    Language lang = datatxtResponse.lang != null ? new Language(datatxtResponse.lang) : null;
```

Not sure why this fries to cast the UriRef - probably item.getKey() to Serializable, but removing the logging definitely solves the issue. I guess it has something to do with the inline if and generic type removal.

In any case this logging is problematic as regardless of the LOG level `GSON.toJson(datatxtResponse)` is called - what I assume to be an expensive operation.

**Comment by westei** [comment]
fixed by https://github.com/fusepoolP3/p3-datatxt-stanbol/commit/2c9abe1ee2c75be5d08d4278ad8f913cf9d4ab9a
